name: country_flags_flutter
description: A flag flutter package. Use for showing flags. All flags came from https://github.com/lipis/flag-icons/releases/tag/v4.1.4 .
version: 1.0.1
homepage: https://github.com/pauli2406/country_flags_flutter_

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.0+1
  enum_to_string: ^2.0.1
  vector_graphics: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - res/1x1/
    - res/4x3/
